### ISSUE TITLE
Add benchmark

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#121]
We can add a sub-project `finch-benchmark` with JMH-based benchmark to test core basic blocks. I would pay a special attention for `RequestReader` abstraction, which is the cornerstone of the Finch applications. We can also test `finch-json` project in the same benchmark.

**Comment by vkostyukov** [comment]
We can also test `Router`.

**Comment by vkostyukov** [comment]
As discussed in the Gitter channel, we might want to test different JSON libraries supported in Finch.

**Comment by travisbrown** [comment]
I've just been putting together some initial benchmarks, since I want to keep an eye on the performance impact of the API additions and changes I'm making. I'll have a pull request ready this morning, but in the meantime I thought people might find this interesting:

```
[info] i.f.b.s.argonaut.ArgonautBenchmark.userOperations  avgt   20  181.007 ± 5.217  ms/op
[info] i.f.b.s.finagle.FinagleBenchmark.userOperations    avgt   20  157.384 ± 5.480  ms/op
[info] i.f.b.s.jackson.JacksonBenchmark.userOperations    avgt   20  157.506 ± 4.963  ms/op
[info] i.f.b.s.json4s.Json4sBenchmark.userOperations      avgt   20  180.603 ± 4.645  ms/op
```

There's no noticeable difference between using Finch with Jackson over the vanilla Finagle HTTP API (also with Jackson), and while you pay a little more for Argonaut and Json4s, it's not much (~14%).

**Comment by travisbrown** [comment]
We can close this now that #266 is merged, no?

**Comment by vkostyukov** [comment]
Sure. Let's close this.
