### ISSUE TITLE
Publish latest release to Maven Central

### ISSUE THREAD

**Issue by hmhagberg** [finagle/finch#1237]
Latest version according to this repository is 0.32.1 but latest available in Maven Central is 0.31.0. Would it be possible to publish 0.32.1 as well?

**Comment by sergeykolbasov** [comment]
Hi @hmhagberg 

If you're looking for `finch` artifact with `com.twitter.Future` then it's deprecated and not getting updates. Otherwise, `F[_]`-polymorphic finch is available under `finchx` name.

We're going to change `finchx` name in the next release to `finch` and by that finish the deprecation cycle.

**Comment by hmhagberg** [comment]
Alright, that explains. Thanks for the prompt reply!

**Comment by MaximilianoFelice** [comment]
Had been struggling with this same issue for a few hours. Why is this not documented on the main page until the deprecation cycle finishes?
