### ISSUE TITLE
How to filter a group of endpoints but not others

### ISSUE THREAD

**Issue by benjumanji** [finagle/finch#1262]
I'm sorry if this is a stupid question, but I have _tried_ reading and understanding what happened in #1080 and I cannot for the life of me see how it answers the question posed in #1051. The types just don't seem to line up, and the middleware example has a bunch of middleware attached to a single bootstrap. I still don't see any method to slap together endpoints in a coproduct and then apply middleware and serve it, along with other unfiltered endpoints.

Any pointers gratefully received.

**Comment by sergeykolbasov** [comment]
Hello

PR #1080 does answer #1051 simply because of signature of middleware (compiled endpoint): 
```scala
Kleisli[F, Request, (Trace, Either[Throwable, Response]] == (Request => F[(Trace, Either[Throwable, Response])])
```

So you can compile your endpoints into `Endpoint.Compiled[F]` (Kleisli), and then create a "filter" which is going to be another Kleisli function with the similar signature, then slap them together and feed into `Bootstrap`.

Example could be find here: https://github.com/finagle/finch/blob/master/examples/src/main/scala/io/finch/middleware/Main.scala

You can't apply it to subset of endpoints though, so for having unfiltered endpoints you would need manually skip filtering inside of your own filter based on the `Request` properties, would it be path, method or whatsoever

**Comment by benjumanji** [comment]
> You can't apply it to subset of endpoints though

I guess this is what had me confused because that seems to me to be what #1051 was about. In any case, I have been playing about more with, and I think I have a nice solution. Thanks for your help!
