### ISSUE TITLE
Use crazy scalac flags

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#129]
See details here: http://tpolecat.github.io/2014/04/11/scalac-flags.html. We probably might want to use those flags.

**Comment by rpless** [comment]
I've started adding flags to the compiler and have run up against some interesting warnings:
- `Xlint` - "it is not recommended to define classes/objects inside of package objects" -- This happens all over the project
- `xLint` - "Selecting value Db from object Main, which extends scala.DelayedInit, is likely to yield an uninitialized value" -- -Xlint causing trouble again
- `Ywarn-value-discard` -- This actually raises a bunch of warnings in our tests, especially around calling `intercept`.

The first warning suggests a pretty massive restructuring of Finch might need to happen. Basically, we can't define classes/traits inside package objects.
For the second warning, I probably just need to fiddle with where DB is defined (will probably put it in its own `object`).
The third warning is more annoying than anything else because we are intentionally discarding those values.

Additionally, I'd like to `-Xfatal-warnings` to make warnings to be fatal, but cannot at the moment because of #86.

Thoughts on these (especially issue 1, 3, and using `-Xfatal-warnings`)?

**Comment by vkostyukov** [comment]
Nice job @rpless on this comprehensive analysis!

I think we can postpone enabling `Xlint` flag for now (I have some plans on how to reduce the amount of code in `package.scala` classes, but this is not urgent at all). We can definitely enable `xLint` and `-Xfatal-warnings` (once we fix #86). I'm not sure I understood `Ywarn-value-discard` flag semantic. Do we really use `intercept`? I was thinking I replaced them all with `an [Exception] should be thrownBy`. But it's probably the same as `intercept`.

**Comment by rpless** [comment]
We still have a couple of `intercept`s hanging around and its also happening on `an [Exception] should be thrownBy`.

**Comment by vkostyukov** [comment]
Done by @rpless.
