### ISSUE TITLE
Does this look like "idiomatic" Finch?

### ISSUE THREAD

**Issue by mfirry** [finagle/finch#209]
Hi, I'm trying to make a (rather silly, I admit) comparison between a few web framework for Scala.

What's important for me is the "look-and-feel" sort of  experience with them.

I'd like to know if I got Finch alright: [take a look](https://github.com/mfirry/web-frameworks-templates/blob/master/finch/src/main/scala/WebServer.scala)

I've also found a little issue: importing both io.finch._ and io.finch.route._ produced ambiguity on the Endpoit object.

Thanks!

**Comment by vkostyukov** [comment]
Hi @mfirry!

That is exactly what we're trying to understand right now - how _good_ Finch code looks like. The brief explanation and possible answers are in [this gist](https://gist.github.com/vkostyukov/e0e952c28b87563b2383).

Regarding the name conflicts. It's also a known issue and [it's mentioned](https://github.com/finagle/finch/blob/master/docs/route.md#filters-and-endpoints) in the documentation.

Otherwise, your approach looks pretty good and fits well into the current understanding of _idiomatic_ Finch style. Once we resolve the problem mentioned in the gist, I will send you a PR with _enhanced_ style. How does it sounds?

**Comment by mfirry** [comment]
Hi @vkostyukov and thanks for the super-quick reply.

Don't bother with the PR. This is really just a "rainy sunday" project for me.
I'll keep following Finch and update my thingie no problem.

One thing I'd like to add is:
I loved being able to *one-line* like this: ```Get /> Ok(Json.arr(1, 2, 3)).toFuture``` but apparently there was no (easy?) way to do it with text/plain responses. Or am I wrong?

**Comment by vkostyukov** [comment]
You should be able to write `val e: Endpoint[HttpRequest, HttpResponse] = Get /> Ok("plain/text").toFuture`.

**Comment by mfirry** [comment]
I tried. I get
```could not find implicit value for parameter encode: io.finch.response.EncodeResponse[io.finch.route.string.type]```

The endpoint looks like: ```Get / string /> Ok(string).toFuture```

**Comment by vkostyukov** [comment]
You're trying to create an HTTP response from type `Router`, since `string` is an instance of type `Router[String]`, a router that extracts string value from the route. You can change it in a way like this:

```scala
val e: Endpoint[HttpRequest, HttpResponse] = Get / string /> Ok(_).toFuture
```

**Comment by mfirry** [comment]
That doesn't work either

```missing parameter type for expanded function ((x$1) => Get.$div(string).$div$greater(Ok(x$1).toFuture))```

**Comment by vkostyukov** [comment]
Yeah. You should probably wrap closure with `{}`:

```scala
val e: Endpoint[HttpRequest, HttpResponse] = Get / "string" / string /> { Ok(_).toFuture }
```

**Comment by mfirry** [comment]
Yeah great. Thanks a lot again!

**Comment by vkostyukov** [comment]
Np. Feel free to ping in case of any questions either here or in Gitter room.
