### ISSUE TITLE
Investigate usability of "micro" package

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#215]
In order to make further steps, we have to understand whether or not Finch will be focused on "micro" style.

**Comment by ImLiar** [comment]
Is there a simple way to combine simple `RouteN` with `PRequestReader` within one route?

Something like
```

val filterReader = param("name") ~ param("sort") ~> SomeFilter
...
Get / "catalog" / "page" / int ~ filterReader /> someFn
...
def someFn(page: Int)(filter: SomeFilter)`

```

it would be super useful to process requests with params from route, payload etc with just one line

**Comment by vkostyukov** [comment]
It's totally possible. You can look at [playground example](https://github.com/finagle/finch/blob/master/playground/src/main/scala/io/finch/playground/Main.scala#L54). The idea is following:

1. You can route request directly to `Micro` if there is no route params
2. You can route request to a function that return `Micro` if there are router params

```scala
val get10: Micro[Int] = Micro.value(10)
def get10xA(a: Int): Micro[Int] = Micro.value(10 * a)

val endpoint = 
  Get / "10" /> get10 |
  Get / "10/ "x" / int /> get10xA
```

**Comment by vkostyukov** [comment]
Sorry, I probably wasn't clear. For now the only way to do it is to deal with type `RouterN[Micro[A]]`, which is a `RouterN` _composed_ with `Micro` and called `Endpoint`. Is it something that you wanted @ImLiar?

**Comment by ImLiar** [comment]
Well, probably it is. I got sick a little, so I'll check it out later. Thx @vkostyukov

**Comment by mfirry** [comment]
Hi, I've been (briefly) fooling around with `Micro` and what's hard to get (for me) is how to write functions and then sort of attach them to Finch endpoints.

I found your playground example a little bit too much in that it also deals with filters and custom requests and so on.

If I don't look at that I can only find simpler example (like this `get10` and `get10xA` one).

This basically shows how you can use `Micro.value` and just have your stuff in there.

Now suppose I have some code that does some computation... say
```def getAge(userId: Int): Future[Int] = { /* some code returning a Future[Int] */ }```

How do I attach it my `Get / "age" />` thingie?

Do I JUST wrap the function call inside a `Micro.value`? Is that it?

**Comment by vkostyukov** [comment]
Hi @mfirry!

Thanks for the feedback!

There is probably no docs for this, but there are 2 new combinators described in [release notes](https://github.com/finagle/finch/releases/tag/0.6.0): `~>` and `~~>` that allow you to compose `Micro[A]` with `A => B` and `A => Future[B]` correspodningly.

You'r example would look something like this:

```scala
def getAge(userId: Int): Future[Int] = ???
val endpoint = Get / "age" /> (param("userId") ~~> getAge)
```

**Comment by mfirry** [comment]
Awesome! Thanks so much.

**Comment by penland365** [comment]
Howdy, I got the chance to dive into the `Micro` stye pretty heavily at the end of last week - I'm looking at this style for my next project.  Two things:

1.) When I first started playing w/ it, I got super excited at the ability to compose + separate out business logic. Then after a couple of hours I realized . . . 

2.) It feels like the abstraction `HttpRequest => (A => B) => HttpResponse`  is a bit incomplete at this stage, due to the fact that there is a lot of business logic wrapped into HttpResponse codes.  Perhaps this in overly Rails~y way to view it ( I work in a Rails shop and I've written a bunch of it ), but the heavily resource biased style of an API is what I'm used to working with ( and to be honest, it's what I expect from an API I consume ).  I'm not sure that `EncodeResponse[B]` is powerful enough to handle all the ( normal ) response codes I would like to provide beyond
```scala
b match {
  case Some(b) => return Ok(b)
  case None    => return NotFound
}
```
As I sit here w/out an coffee this morning, in my head if feels like the abstraction needs to be closer to the form `HttpRequest => ( A => HttpResponseCode[B] ) => HttpResponse`.  Of course, it's entirely possible I'm not seeing the full jigsaw puzzle. However, the vast majority of the time when I'm working on an API my initial thought is, "What is the proper response code to this request"?

I do want to reiterate that I love this style and I fully agree this is where Finch needs to be going. I'm deeply appreciative of this project.

**Comment by vkostyukov** [comment]
Hi @penland365!

Thanks a ton for this feedback!

It's true. You thoughts are similar to mine. That's why there is a ticket about a heterogeneous router (see #221). The motivation for that is basically to provide users more flexibility on what is the proper response. (and this is exactly what confused you) Within a heterogeneous router we no longer stick to the abstraction `HttpRequest => (A => B) => HttResponse` - we're going to deal with a function `HttpRequest => (A => B)`. So, you can serialize any `B` (even an `HttpResponse`).

Quick example:

```scala
val endpoint: Router[User :: HttpResponse :: HNil] = 
  Get / "users" /> User(10) ::
  Get / "health" /> Created.withHeaders("X" -> 10)()
```

@travisbrown and I are thinking about this right now and I hope we will ship something in the next release. So, I would suggest you to wait until that and use a heterogeneous router instead of `Micro`, since the last one will probably die soon (will be deprecated in 0.7.0).

**Comment by penland365** [comment]
@vkostyukov Thanks for the reply!  I had typed up a response earlier, then went to eat lunch and forgot about it. Yeah, the heterogeneous router feels a little closer to what I was mulling over this morning.

**Comment by vkostyukov** [comment]
Micro is going to be deprecated in 0.7.0 since it was probably a bad idea. The current big thing that replacing Micro is Heterogenous Routers #221.
