### ISSUE TITLE
Revise all the implicit conversions

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#238]
We might probably want to move them into the corresponding companion objects (if possible) to make the compilation faster for both Finch contributors and Finch users.

**Comment by vanyacohen** [comment]
I'm happy to help make this happen, but I've encountered some trouble identifying offending code. It seemed like every implicit method I found was already in an object (or trait extended by an object). Would you be willing to help me understand what needs to be fixed?

**Comment by vkostyukov** [comment]
@vanyacohen, Travis and I are addressed a lot of conversions in #278, but I'm pretty sure something is left. Otherwise, we can just close this issue.

**Comment by travisbrown** [comment]
Hi @vanyacohen—one example I just noticed by grepping for `implicit def` is `toOptionalRule` in the `request` package object. Right now you have to import the contents of the package object to get it to apply, and then it's just another implicit conversion in scope that the Scala compiler has to consider all the time. If it were in the `ValidationRule` companion object (since it has `ValidationRule` as both source and target), it wouldn't need to be imported and the compiler would only consider it when it needs an implicit conversion to or from `ValidationRule`.

There are probably at least a few other conversions like this still around.

**Comment by vkostyukov** [comment]
Thanks @travisbrown! `ValidationRule` is probably the lowest hanging fruit for this ticket. Once we fix it we can probably close the ticket.

**Comment by vanyacohen** [comment]
Yes, thanks @travisbrown! I'll go ahead and move toOptionalRule to the ValidationRule companion object and look for similar conversions.
