### ISSUE TITLE
Experiment with Jawn as a parser for finch-argonaut

### ISSUE THREAD

**Issue by travisbrown** [finagle/finch#287]
Jawn supports parsing into the Argonaut AST, which would allow us to replace the stock Argonaut parser while still using the AST, codec type classes, etc. There's a chance this could improve performance, and it wouldn't be too hard to try.

**Comment by rpless** [comment]
Hi @travisbrown, I think this may not be feasible. I've done the conversion [here](https://github.com/rpless/finch/blob/dont-switch-to-jawn/argonaut/src/main/scala/io/finch/argonaut/package.scala#L44), but all of the property tests for decoding now fail. I believe it has something to do with [how jawn handles longs](https://github.com/non/jawn/blob/master/support/argonaut/src/main/scala/Parser.scala#L13), which is to say it doesn't. Unlike argonaut, it has no idea if a value should be read as a double or long, so it defaults to double. Argonaut already knows it should read a long if it is marshalling straight to a case class with longs. This seems to introduce a precision error when we convert the Jawn AST to the Case class.

Examples of how the property tests fail:
Got: ```ExampleNestedCaseClass("",5.605174453385813E214,2648374962344288256,List(),...)```
Should have been: ```ExampleNestedCaseClass("",5.605174453385813E214,2648374962344288310,List(),...)```
The issue is with the third argument.
We can see the difference in the REPL too:
```
scala> java.lang.Double.parseDouble("2648374962344288310")
res0: Double = 2.6483749623442883E18

scala> java.lang.Double.parseDouble("2648374962344288310").toLong
res1: Long = 2648374962344288256

scala> java.lang.Long.parseLong("2648374962344288310")
res2: Long = 2648374962344288310
```
Thoughts?

**Comment by travisbrown** [comment]
Thanks for putting this together! I think we should take this up with the Jawn folks—changing that `jint` implementation to `Json.jNumber(java.lang.Long.parseLong(s))`, publishing locally, and changing your branch to depend on the snapshot makes the tests pass for me.

**Comment by travisbrown** [comment]
I just ran the service benchmarks with this change and almost everything is a touch better (both times and allocation rates), but generally inside the margin of error. There's currently more emphasis on encoding than decoding in the service benchmarks, though.

So I think it's worth trying to get that change into Jawn, and then we can decide whether the improvement (if there actually is any) is worth the extra dependency here.

**Comment by rpless** [comment]
Ok, sounds like a plan. If you haven't already, I can start working on a reduced test case and have a PR for jawn.

**Comment by vkostyukov** [comment]
@travisbrown do you mind sharing the benchmark results?

**Comment by travisbrown** [comment]
@vkostyukov [Sure](https://gist.github.com/travisbrown/2c42914fab71514e5851) (sorry about the format)!

**Comment by travisbrown** [comment]
Oh, and no, @rpless—I made that one little change but haven't started preparing a Jawn PR.

**Comment by vkostyukov** [comment]
Thanks @travisbrown! Looks like it gives us around 3% in both allocations/performance. I would say it worth using Jawn then, especially if we're promoting Argonaut as a preferred JSON backend.

**Comment by travisbrown** [comment]
@vkostyukov That's one run on my desktop machine, which has several browsers open, etc.—we probably want to look a little more carefully before deciding for sure. But I think it's worth the effort.

**Comment by vkostyukov** [comment]
@rpless :+1: for fixing the issue in Jawn!

**Comment by vkostyukov** [comment]
Done in #400.
