### ISSUE TITLE
Imporve Smash

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#315]
I was experimenting with some simple idea: can we be a bit of smarter in smashing. More precisely, can we shams `HNil` and `A` (and vice versa) into just `A` not `A :: HNil`.

Here is an example:

```scala
val Router: Router[Int :: HNil] = Get / "user" / int // used to be just Router[Int]
```

It seems pretty possible to me (and it's almost workable in my branch).

@travisbrown do you have any concerns about that? What I see is a bit of problems with `/>` compositor that should be easy to fix.

**Comment by travisbrown** [comment]
My first reaction was that this just makes `Smash` a little more magical by special casing the single-element case. On second thought I don't think that's necessarily a problem, though, since the mechanics here are supposed to be mostly hidden from the user (unlike the more explicit approach Scodec takes with `dropUnits`, etc., for example). So I think it's at least a reasonable experiment.
