### ISSUE TITLE
Let's publish a web-site compiled from docs

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#339]
@travisbrown and I discussed this some time ago. I believe this is going to be very helpful. The idea is to publish two web-sites:
1. `http://finagle.github.io/finch/docs` - scala doc
2. `http://finagle.github.io/finch/guide` - user guide (current state of the `docs` folder)

**Comment by rpless** [comment]
:+1: here. My feeling is that if we go with this, we should stop doing `gh-pages` deploys with `sbt-unidoc`. Does that sound reasonable?

**Comment by travisbrown** [comment]
@rpless I haven't been doing the `gh-pages` deploys—how is sbt-unidoc involved? We'll still need it to unify the subproject docs, and we'll probably want to continue to use sbt-ghpages (if that's what we're using now)—we just might want to add sbt-site for pulling everything together.

Also, @vkostyukov, do you think it's worth setting up `/stable/` and `/nightly/` subdirectories? I like this change in part because it allows us to update the docs as we change the API, but actually publishing the updated docs would be useful as well.

**Comment by vkostyukov** [comment]
@travisbrown totally! Forgot to mention that. Maybe we should go with `/stable/` and `/snapshot/` then since we don't really publish things every night?

**Comment by travisbrown** [comment]
@vkostyukov Sounds good to me!

**Comment by rpless** [comment]
@travisbrown you're right it is the `gh-pages` plugin. I had thought is unidoc because they have the usage [instructions](https://github.com/sbt/sbt-unidoc#how-to-publish-scala-unidoc-to-github-pages) on their readme. 

My point was less about unidoc and more that I'm not sure we should be publishing the same docs to two different places. I think it could become confusing if they get out of sync.

**Comment by travisbrown** [comment]
@rpless Do you mean no `/stable/` and `/snapshot/` duplication? I definitely agree that we shouldn't be publishing the same version of something to multiple places, but do think having docs for both versions would be useful.

If we do have `/stable/` and `/snapshot/` versions of everything, ideally I think we'd have `<link rel="canonical" ... />` links to the `stable` version in each `snapshot` page for the sake of SEO and clarity. I did something similar to this as [a one-off fix for Util's docs](https://github.com/twitter/util/pull/106) last year, but don't know how practical it would be to automate as part of the build.

**Comment by rpless** [comment]
I think we should have `stable` and a `snapshot`. You kinda need that if your a user that wants to use the snapshots. I don't think we should continue to maintain the `gh-pages` branch if we move docs to `http://finagle.github.io/finch/`.

**Comment by vkostyukov** [comment]
We should try adopting that sbt-microsites project in Finch. If I recall correctly, @muuki88 had offered some help on this front.

**Comment by muuki88** [comment]
@vkostyukov yeah, I can give it a try when I got some time on the weekend.

However I'm not sure how the `stable` / `snapshot` build could look like. `sbt-microsites` doesn't support any kind of versioning IIRC, so we would have some special step in the release that copies the content from `snapshot` to `stable` during a release.

**Comment by spockz** [comment]
We could run the publish step as part of the release?

**Comment by vkostyukov** [comment]
I know it sounds like a miracle, but it's done in #751.
