### ISSUE TITLE
Enriched version of Endpoint with "safe" operations

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#405]
One of the downsides of HTTP is that everything is string-based (headers in particular). Thus it's prety easy to mess things up and type `ConentType` instead of `ContentType` and so on. What we can do in order to make it safier is to provide an implicit class `EndpointOps` (or something like) with "safe" version of `withHeader` methods for particular cases.

Let's discuss the list of methods we want to start with. Perhaps we should pick the most common use cases:
- `withContentTypeJson`
- `withContentTypeHtml`
- ...

**Comment by amartinsn** [comment]
I really like the idea of having enriched Endpoints. The motivation on my scenario is because we need to set `cache-control` headers for specific endpoints, and doing that manually is quite boring. At the same time, there are several possible variations of cache-control configuration (http://www.mobify.com/blog/beginners-guide-to-http-cache-headers/), which makes it difficult to come up with a method that covers them all. In our case, we created this method:

```
.withCacheControl(Public, 5 minutes)
```

which sets `cache-control` header to `public,max-age=300`, but I need to continue evolving that.
