### ISSUE TITLE
Circe error accumulation

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#587]
As Travis described [on Gitter ](https://gitter.im/finagle/finch?at=5709750fddb5a2cf3bbae825).

**Comment by wennergr** [comment]
More then happy to help out here, but I would need some help ;)

Some initial thoughts and questions:

## Issue One, decode function
We would need a slightly modified version of the circe [Parser.decode](https://github.com/travisbrown/circe/blob/master/core/shared/src/main/scala/io/circe/Parser.scala)

Best case (for me) would be a decode function with the following signature:
```scala
def decode[A](input: String)(implicit d: Decoder [A]): Xor[Nel[Error], A]
```

This will however not work because `Nel` is invarient and this function code return both `ParsingFailure` and `DecodingFailure` (and these relates to error Error through sub-classing).

We could instead use **list** instead of **nel**:
```scala
def decode[A](input: String)(implicit d: Decoder [A]): Xor[List[Error], A]
```

## Issue Two, RequestErrors
The Endpoint logic `StringEndpointOps.as` will create a new Error.NotParsed with our RequestErrors as the cause. E.g we will end up with our multiple errors wrapped inside the NotParser error (cause property). (Not what we want)

There are multiple ways to fix this but they are all non additive changes. Any thought on this would be appreciated.

**Comment by travisbrown** [comment]
@wennergr I've just opened [a quick PR](https://github.com/travisbrown/circe/pull/260) that adds a `decodeAccumulating` method to `Parser` in circe (we'll eventually want this kind of thing for multiple web service frameworks, so we might as well do it there).

Just because `NonEmptyList` is invariant, that doesn't mean upcasting the element type isn't safe—you just have to do it "manually".

**Comment by bergmark** [comment]
This would be super nice to have!

Did anyone start working on this? Is what @wennergr suggested the right way to go? I'd be interested in helping out if we can decide how to do this.
