### ISSUE TITLE
How to add a tracer?

### ISSUE THREAD

**Issue by vasily-kirichenko** [finagle/finch#628]
In pure Finagle one can add a tracer like this:

```java
SamplingTracer tracer = new HttpZipkinTracer();

ServerBuilder.safeBuild(
    new Backend(),
    ServerBuilder.get()
        .tracer(tracer) <--------- here
        .codec(Http.get().enableTracing(true))
        .bindTo(new InetSocketAddress(InetAddress.getLoopbackAddress(), 9000))
        .name("backend"));
```
(https://github.com/openzipkin/zipkin-finagle-example/blob/master/src/main/java/finagle/Backend.java)

I cannot find a way to add a tracer in a Finch service like this:

```scala
object WebServer extends TwitterServer {
  def main() = {
    val api: Endpoint[String] = get("person" :: string) { name: String =>  Ok("foo")  }
    
    val service =
        api
          .toService
          .tracer(new HttpZipkinTracer()) <------ does not compile

    val server = Http.server.serve(":29002", service)
    onExit { val _ = server.close() }
    Await.ready(adminHttpServer)
  }
}
```

**Comment by vkostyukov** [comment]
Finch doesn't operate on a layer that involves tracing. Finagle does. That said, tracer should be passed to a Finagle server builder. Your first example should work if instead of `new Backend()` you pass `api.toService`.

It doesn't relate to this question, but we're generally recommending using the `with`-API instead of `ServerBuider`. Try something between the lines:

```scala
 val server = Http.server
  .withTracer(new HttpZipkinTracer())
  .serve(":29002", service) // server is a Finagle `Service`
```
