### ISSUE TITLE
Error: "code too large" and then broken at compile time 

### ISSUE THREAD

**Issue by x72002168** [finagle/finch#670]
I have a project with lots of API functions (more than 70), when I use :+: to merge all of these functions, something like:
val export = api1 :+: api2 :+: api3  :+: api4  :+: api5  :+: api6  :+: api7 :+: api8
val result = export .toService

It will cause the error, here is the message:
Could not write class com/e104/master/oauth/server$ because it exceeds JVM code size limits. Method delayedEndpoint$com$e104$master$oauth$server$1's code too large!

But if I try to separate them to few groups and merge, something like: 
val export = (api1 :+: api2) :+: (api3  :+: api4)  :+: (api5  :+: api6)  :+: (api7 :+: api8)
val result = export .toService

It won't cause the error.
Different ways for separating groups, for example:
1. val export = (api1 :+: api2) :+: (api3  :+: api4)  :+: (api5  :+: api6)  :+: (api7 :+: api8)
2. val export = api1 :+: (api2 :+: api3)  :+: (api4  :+: api5  :+: api6)  :+: (api7 :+: api8)

Some will fail, and some will success. I'm not sure if it's a bug, or I shouldn't use the way to merge the API functions. I found that the releases version Finch 0.11-M1 (https://github.com/finagle/finch/releases) had mentioned this problem, but my project had never broken at run time, only at compile time. 

It seems have no solutions so far. I wonder if anybody have any suggestions for the problem.

**Comment by vkostyukov** [comment]
Thanks, @x72002168, this is very interesting. Which Scala version are you using?

**Comment by x72002168** [comment]
@vkostyukov The version is 2.11.7 .

**Comment by omerzach** [comment]
I'm seeing this too on 2.12.0 with finch 0.11.1 :(

**Comment by vkostyukov** [comment]
@omerzach How many endpoints do you have? Does grouping help in your case?

**Comment by omerzach** [comment]
We have 67 endpoints total (files with 2, 4, 10, 2, 8, 28, and 13 `:+:`ed together then another file that combines each of those as `("foo" :: fooEndpoints) :+: ("bar" :: barEndpoints) :+: …`

It worked until I added one of those files of 2 endpoints, so maybe @x72002168 and I are both right near a cutoff point.

And yep, grouping solves the problem.

(Sorry for not including any details yesterday, hit the issue just as I was wrapping up work for the night.)

**Comment by vkostyukov** [comment]
Very interesting. Thanks a lot, @omerzach! Looks like ~70 composed endpoints compile into something bigger than 65k bytecodes. I will look into that as part of 0.14 milestone.

**Comment by od0** [comment]
@vkostyukov any new findings on this front? I'm at around 60 composed endpoints split into 7 files. Compilation is fine (a bit slow but no huge issues) but the macros are pretty rough on IntelliJ - CPU and heap go through the roof in the files where endpoints are defined and syntax highlighting never fully completes in the main API file where all the endpoint definitions are finally composed together. I really love Finch, but the the dev experience for other people on my team is making it hard to stick with it.

**Comment by vkostyukov** [comment]
Thanks for the patience @od0!

I totally understand the struggle of defining 60+ endpoints with Finch. I'm really not saying it wasn't designed for "big" applications, but relying on types while composing endpoints has its flaws. It's pretty obvious when you think about it: in order to take advantage of types, you have to keep them around. This means pushing both the compiler and the IDE to the limits. Honestly, I'm not aware of any other Scala library operating Shapeless `HList`s with 70+ elements/types. Finch is quite unique in that sense.

While we're trying to make some progress on the IDE front (see #631), we haven't spent much time worrying about the compiler limits yet. As far as the planning goes, the current priority is to push 1.0 with a stable API for an endpoint. I'd imagine compilation speed and IDE support will be our first priorities after 1.0.

**Comment by vkostyukov** [comment]
Oh, one more thing. `Bootstrap` (see https://github.com/finagle/finch/releases/tag/0.16.0-M1) should help you to break down endpoints even further. My guess is that you can define ~70 endpoints per `Bootstrap.serve`, which makes it effectively "unlimited" given you might call `serve` lots of times.

**Comment by vkostyukov** [comment]
@od0 and others,

I'm going to close this for now given `Bootstrap` helps to mitigate this.

I wanted to take some time and reflect on @od0's comment from a year ago since I think we accomplished quite a lot since that time.

> I'm at around 60 composed endpoints split into 7 files. Compilation is fine (a bit slow but no huge issues) but the macros are pretty rough on IntelliJ - CPU and heap go through the roof in the files where endpoints are defined  ...

0.18 has quite significant compile time improvements (see #924). In addition to that, [circe-derivation](https://github.com/circe/circe-derivation) (assuming you use Finch with Crice) made an outstanding progress in the same space and is a great alternative to Shapeless-powered derivation.

> ... and syntax highlighting never fully completes in the main API file where all the endpoint definitions are finally composed together. I really love Finch, but the dev experience for other people on my team is making it hard to stick with it.

As of IntelliJ 2017.3 and Finch 0.16-M4 there are no outstanding issues with syntax highlighting. See more details in #631 and https://youtrack.jetbrains.com/issue/SCL-11386.
