### ISSUE TITLE
Unable to start finch app (AbstractNioWorkerPool warning)

### ISSUE THREAD

**Issue by divergence082** [finagle/finch#739]
Code:
```
  private val api: Endpoint[Seq[Resource]] = get("fold" :: grid) {
    g: Grid => fold(g).map(res => Ok(res))
  }

  Http.server.serve(":8085", api.toServiceAs[Application.Json])
```

Output:
```
[info] Running space.divergence.grid.service.FoldApp 
Feb 07, 2017 5:53:31 PM com.twitter.finagle.Init$ $anonfun$once$1
INFO: Finagle version 6.41.0 (rev=95eedf5f41f78414fae25d93cc8fae02eeb5a75d) built at 20161220-164650
Feb 07, 2017 5:53:41 PM org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool
WARNING: Failed to get all worker threads ready within 10 second(s). Make sure to specify the executor which has more threads than the requested workerCount. If unsure, use Executors.newCachedThreadPool().
[success] Total time: 19 s, completed Feb 7, 2017 5:53:41 PM
```

Dependencies:
```
"com.github.finagle" %% "finch-core" % "0.12.0",
"com.github.finagle" %% "finch-jackson" % "0.12.0"
```

```
scalaVersion := "2.12.1"
```

**Comment by rpless** [comment]
The warning is a [known issue with Finagle](https://github.com/twitter/finagle/issues/581), but I haven't noticed any real problems running the one app that I do have using Scala 2.12.

However, I don't think this is the issue here. I think if you change the last line of your app to:
```scala
Await.ready(Http.server.serve(":8085", api.toServiceAs[Application.Json]))
```
it will work. Basically, the application is actually just completing and exiting successfully if you do not `Await` on the server.

**Comment by divergence082** [comment]
Thanks! It works!

**Comment by rpless** [comment]
@divergence082 Glad to help! You may also want to check out our [gitter channel](https://gitter.im/finagle/finch) too. There a lot of great folks who hang out there and are always willing to help with Finch questions.
