### ISSUE TITLE
Failed outputs are rendered as responses with no body

### ISSUE THREAD

**Issue by aroberts** [finagle/finch#765]
I'm trying to upgrade to 0.14 (from 0.11), and I'm encountering an issue with custom error responses. I am using finch-circe, and I have a custom `Encoder[Exception]` which is imported into the implicit scope where I'm calling `toServiceAs`, but I don't see my custom output. Also, logging that I injected into my encoder never fires, which further indicates that my code is not getting run.

I see responses that look like:
```
HTTP/1.1 400 Bad Request
Content-Length: 0
Date: Fri, 21 Apr 2017 18:05:39 GMT
Vary: Origin
```

@vkostyukov notes that the date header means Finch is processing the response, because finagle by itself doesn't have that. However, even if there was no message, the default `Encoder[Exception]` instance would seem to return `"{message:null}"` in the body, in the event of a missing message. It's not clear why the bodies are missing entirely.

**Comment by aroberts** [comment]
It appears that omitting 
```scala
    .configured(Http.Netty4Impl)
```

was the cause of this issue in my particular case. I'm going to close this issue, as I think it's too tied up in my personal dependency situation to have a clear path forward.

**Comment by rlazoti** [comment]
I was having the same issue you reported (Bad Request responses with no body content).
If I understood correctly, it's caused because there're 2 encoders for Exception type. 

So there're two ways to "fix" it temporally:

1 - Removing your encoder (Encoder[Exception])
2 - Removing the default Encoder.
I ended up doing this with the following import:

```scala
import io.finch.circe.{
  jacksonSerializer,
  decodeCirce,
  encodeCirce
}
```
Instead of 

```scala
import io.finch.circe._
```

**Comment by aroberts** [comment]
I created a minimal reproduction of the issue: https://github.com/aroberts/finch-14-errors

@rlazoti I hear what you're saying, but why would the compiler not resolve the implicit resolution according to precedence rules? Also, version 0.11 has an `Encoder[Exception]` instance, but does not exhibit this issue. I appreciate the workaround but I still think there's some underlying weirdness here that should be fixed.

**Comment by rpless** [comment]
My initial thought was that we should have been seeing an ambiguous implicit values error from the compiler. If you turn on the `-Xlog-implicits` compiler option you will see something like this:
```encodeCirce is not a valid implicit value for io.finch.Encode.Aux[Exception,io.finch.Application.Json] because:
[info] hasMatchingSymbol reported error: ambiguous implicit values:
[info]  both value encodeExceptionCirce in trait Encoders of type => io.circe.Encoder[Exception]
[info]  and value encodeException in object RestServer of type => io.circe.Encoder[Exception]
[info]  match expected type io.circe.Encoder[Exception]
[info]   val api: Service[Request, Response] = (ping :+: error).toServiceAs[Application.Json]
```
This is being logged when the compiler attempts to summon `encodeCirce` (the Finch Encode from `finch-circe`). In order to do so successfully, it must summon a circe `Encoder`. I believe it cannot resolve this encoder because `encodeExceptionCirce` (from finch-circe) and `encodeException` have the same precedence and thus we see logging from above. As a result, it summons an [Encode with lower precedence](https://github.com/finagle/finch/blob/master/core/src/main/scala/io/finch/Encode.scala#L50) instead. This encoder uses an empty Buf for the content body.

There were a lot of changes between 0.11 and 0.14 and that area of the code has changed quite a bit between the two versions. I do agree that its not ideal, but I don't yet know how to fix it. We'll need to figure out if there is somewhere that we can move the `encodeExceptionCirce` such that it doesn't get in the way. For the moment, I'd stick with @rlazoti's suggestion.

**Comment by vkostyukov** [comment]
Thanks @rpless! Do you think 

- moving `encodeException` under `LowPriority*` and
- somehow lowering the priority of `encodeException` (from finch-circe)

would help here?

**Comment by rpless** [comment]
I didn't think moving `encodeException` to `LowPriority*` would help, but I tried anyway just to confirm that it wouldn't.
I'm not sure how we would lower the priority of `encodeExceptionCirce` in finch-circe. There isn't anywhere to move it relative to a user defined Encoder that would change its `relative weight` as far as the [rules of static overloading resolution](http://www.scala-lang.org/files/archive/spec/2.12/06-expressions.html#overloading-resolution) are concerned (this is section on implicit conversions, but the same rules apply to resolving implicit values).
The only solutions I can think of at the moment are:
 -  stop providing `encodeExceptionCirce` from `io.finch.circe._`
 - provide it from a trait that can be mixed into an application. maybe a `DefaultCirceEncoders` or something
 - document it as a known issue

I don't have any strong feelings on any of these yet.

**Comment by vkostyukov** [comment]
I like the first option. I think we should only provide a default instance from `Encode.encodeException` and don't try to be smart withing JSON sub-projects. I'm happy to open a PR that removes all those instances unless somebody else wants to volunteer?

**Comment by rpless** [comment]
@vkostyukov sounds good to me. We'll have to make sure to update the docs too on the next release. If you haven't already started in on removing them, I can start pulling them out.

**Comment by vkostyukov** [comment]
Fixed in #775.

**Comment by anatoliykmetyuk** [comment]
Can anyone please clarify on how exceptions are rendered now? Currently, when I return say a `BadRequest` of an exception with some text, on the client side it shows up as a response code `400` with no message.

**Comment by rpless** [comment]
Hi @anatoliykmetyuk, it looks the rendering of the docs is a little messed up, but if you look at the bottom of [this section](https://finagle.github.io/finch/user-guide.html#errors), it shows that you can do this:
```scala
implicit val encodeExceptionCirce: Encoder[Exception] = 
  Encoder.instance(e =>	
    Json.obj(“message” -> Option(e.getMessage).fold(Json.Null)(Json.fromString)))
```
I'll try to fix those up later so its clearer how to render errors.

**Comment by ComFreek** [comment]
Note that <https://finagle.github.io/finch/user-guide.html#errors> (that @rpless referenced above) contains a much more elaborated code snippet now than the comment above.
