### ISSUE TITLE
Forking Rerunnable

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#793]
I figured we should have an explicit discussion about that even though we chatted briefly several months ago. catbird-util is the only dependency of finch-core that also requires finagle-http, which means we usually have to publish it first (well, Travis has to). Shame on me, I completely forgot about that last time I did a release so we did it later (see #788).

I think having `Rerunnable` defined under `io.finch.internal` would go a long way in simplifying our release process and the dependency graph. So I'm voting for forking it in 0.16 and dropping the catbird-util dependency.

@travisbrown, @rpless what do you think?

**Comment by travisbrown** [comment]
This sounds reasonable to me, although if Finch ever wanted to use the Cats type class instances in catbird that would mean more duplicated code.

I know there are a few people using catbird outside of the context of Finch, but I'm not sure whether they're also using Finch and would need interop if there are two versions of this. I think it's safe to assume that's not the case, though.

Alternatively I could share the ability to publish to `io.catbird` so that it's not blocked on me (I've been trying to get releases out in a timely fashion but I know that might not always be the case).

**Comment by vkostyukov** [comment]
Thanks @travisbrown! Sorry if I made it sound like you're guilty. It's totally me who wanted to get the release out of the door as fast as possible so this catbird dependency completely slipped my mind. Your dedication to the catbird releases, on the other hand, is unquestionable - catbird release happened before Finagle release was even announced (we're still working on a blog post).

**Comment by vkostyukov** [comment]
@travisbrown Do you happen to know if people use `Rerunnable` outside of Finch context?

**Comment by travisbrown** [comment]
It's at least possible that Stripe will be using it at some point before too long (outside the context of Finch). I'd be a little reluctant to have it in two places, especially since some Finch users are going to need a catbird dependency and then they'll have the confusion of two `Rerunnable`s floating around.

What do you think about moving all of catbird into Finch as a standalone root module (finch-util or finch-kernel or finch-cats or something)? Then we don't have duplication, and non-Finch catbird users don't have to either reinvent stuff or depend on the rest of Finch. The only downside I can think of would be for non-Finch users if a Finch release was excessively delayed after a Finagle release, but that seems unlikely.

**Comment by vkostyukov** [comment]
Yeah, as much as I'd like to do that for the sake of simplifying Finch releases, I believe catbird deserves to be its own project.

What if we rename Finch's `Rerunnalbe` (I guess, `io.finch.internal.Rerunnable` is already a different name)? Do you think it would make a trick? It seems to me that `Rerunnable` is pretty standalone and isolated and I'm not seeing it interacting with other catbird types. So if we just rename (to avoid visual ambiguity), I don't see why else it could cause problems.

**Comment by crispywalrus** [comment]
Rerunnable it  in catbird-util and depends on twitter-util not finagle-http, not that that changes the fact that upgrading the twitter eco-system requires publishing catbird first. That said we do use catbird outside of finch (we have some iteratee based processes) As long as I can have a Rerunnable effect from catbird that doesn't conflict with the finch version I don't see how this would cause issues.

**Comment by rpless** [comment]
Not a huge fan of the depulicating `Rerunnable`, but I do like the idea of dropping the dependency if we don't need it for anything else and our Rerunnable doesn't conflict with catbird-util. In the end, I think duplicating it as `io.finch.internal.Rerunnable` is probably the way to go. We'll just have to make a note in the release notes that anyone relying on the transitive dependency will need to explicitly import catbird-util now.

**Comment by vkostyukov** [comment]
From what I'm hearing, we're all on the same page. Let's fork it in 0.16 and see how things go. We can always bring the dependency back.

**Comment by vkostyukov** [comment]
I opened a PR here: #798 798

**Comment by vkostyukov** [comment]
I'm closing this for now. Based on the discussion here, we're not forking `Rerunnable` (at least, until 1.0).
