### ISSUE TITLE
Finch doesn't see request body with in-process client+server

### ISSUE THREAD

**Issue by s-nel** [finagle/finch#852]
Problem: when I create a Finagle client and send a Post request directly to the `Service[Request, Response]` returned from `Endpoint.toService` the request body sent to the Finch service it isn't seen by Finch and I get 400 response "Required body not present in the request." This only happens when I send requests directly by method calling. It doesn't reproduce when I call `serve` on the service and send requests over the network.

Tests reproducing results: https://github.com/s-nel/finch-short-circuit-service-bug

Basically, I think this should work but it doesn't:

```
    val request = Request(Method.Post, "/foo")
    request.setContentString("foo")
    Await
      .result(post("foo" :: stringBody) { (s: String) =>
        Ok("")
      }.toService.apply(request))
      .status mustBe Status.Ok
```

If I change `stringBody` to `stringBodyOption`, the endpoint is correctly matched, but the option is `None`. If I `serve` the Finch service on a port and use a client from `Http.client.newClient` the Finch service works as expected.

If I do the same thing In Finagle, it works just fine:

```
val request = Request(Method.Post, "/foo")
    request.setContentString("foo")
    Await
      .result(new Service[Request, Response] {
        def apply(req: Request): Future[Response] = {
          req.contentString mustBe "foo"
          Future.value(Response())
        }
      }.apply(request))
      .status mustBe Status.Ok
```

Use case: I have a service oriented architecture, and I want to run integration tests to test that clients and services can talk to each other. To reduce complexity of test infrastructure and improve execution time of tests I want to avoid `serve`ing the services and just send requests to them directly.

I've reproduced this issue in Finch 0.13.1, 0.15.1, and 0.16.0-RC1

**Comment by ImLiar** [comment]
Hi @s-nel 

Thank you for this detailed explanation! It seems you also have to specify content-length for request manually:  
```scala
request.contentLength = "foo".getBytes(StandardCharsets.UTF_8).length
```

You could check sources [here](https://github.com/finagle/finch/blob/master/core/src/main/scala/io/finch/endpoint/body.scala#L24)

I guess in case when you start the full server, finagle (or may be even netty), handle this missing header on the fly, but I'm not sure about that.

**Comment by rpless** [comment]
Yeah we do this because of https://github.com/finagle/finch/issues/795. We have to in order to handle optional empty bodies correctly. As part of HTTP, if you have a content body you are kinda supposed to set Content-Length like @ImLiar said. In the case of the example `Service` that you created, its acting exactly as you defined it, because you aren't checking content-length, whereas we have to check it inside Finch. I think your best bet is to either set the content length on the request or have a filter that gets composed with the service during tests, to handle this.

As an aside when you use `Http.server.serve` I believe it will correct http requests that don't include a content length to have the header set, so you shouldn't run into this outside of tests.

**Comment by s-nel** [comment]
Thanks for the quick replies! After specifying content length it works.
