### ISSUE TITLE
path[String] parameters are URL-encoded

### ISSUE THREAD

**Issue by matskoff** [finagle/finch#902]
Is it supposed to keep path[String] url-encoded?
Here is an example:

```
import io.finch._
import com.twitter.finagle.Http
import com.twitter.util.Await

object Main {
    def main(args: Array[String]): Unit = {
        val api: Endpoint[String] = get("hello" :: path[String] :: param("param")) { (expr1: String, expr2: String) =>
            Ok(s"Passed as path: $expr1. Passed as param: $expr2." )
        }

        Await.ready(Http.server.serve(":8080", api.toServiceAs[Text.Plain]))
    }
}
```

Opening the url: http://localhost:8080/hello/1%2B1?param=1%2B1
I see: Passed as path: 1%2B1. Passed as param: 1+1.

Is different behavior on decoding path and url parameters expected? What is the best way to decode path parameters?

**Comment by vkostyukov** [comment]
Interesting. I'd expect this to be decoded in the output. What do you think @rpless, @ImLiar?

**Comment by ImLiar** [comment]
Yea, I think it should be decoded. 

RFC for URI says that
>   A percent-encoding mechanism is used to represent a data octet in a
   component when that octet's corresponding character is outside the
   allowed set or is being used as a delimiter of, or within, the
   component.

Since path and query parts both are components here, I see no reason to apply different rules
